name = "xivpedia"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "SESSION"
id = "081d4af6dba34d319a32590b0745a7c7"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "xivpedia"

[vars]
SITE_URL = "https://xivpedia.pages.dev"
